#!/bin/sh

mount -t proc proc /proc
mount -t sysfs sys /sys
mount -t devtmpfs dev /dev

usb_led=/sys/devices/platform/leds-gpio/leds/tp-link:green:usb1
echo timer > $usb_led/trigger
echo 100 > $usb_led/delay_on
echo 100 > $usb_led/delay_off

echo ">>> Press 's' for a shell."

mkdir -p /root
while ! mount LABEL=tpl /root; do
    while read -t 1 -n 1 input; do
        if [ "$input" = "s" ]; then
            echo
            /bin/sh
        fi
    done
done
echo ">>> Root mounted."

mkdir -p /kexec
if ! cp /root/boot/vmlinux /kexec; then
    echo "!!! Failed to find vmlinux and cmdline!"
    exec /bin/sh
fi
echo ">>> Copied vmlinux and cmdline."

umount /root
echo ">>> Root unmounted."

echo > /kexec/dtb
kexec /kexec/vmlinux \
    --type=elf-mips \
    --dtb=/kexec/dtb \
    --command-line='console=ttyS0,115200 debug machtype=ARCHER-C5 root=/dev/mmc0 rootwait' \
    --force

echo "!!! kexec failed!"
exec /bin/sh
